# Generated by Django 3.1.2 on 2022-06-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jirani', '0002_remove_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='occupants',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='health',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='police',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
